backend:
  name: git-gateway
  branch: master

media_folder: static/uploads
public_folder: /uploads

collections:
  - name: menu-item
    label: Menu Item
    folder: content/menu-items
    create: true
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Type, name: type, widget: hidden, default: menu-item }
      - { label: Price, name: price, widget: number }
      - { label: Description, name: description, widget: text }
  - name: slider-images
    label: Slider Images
    folder: content/slider-images
    create: true
    identifier_field: image
    fields:
      - name: type
        widget: hidden
        default: slider-image
      - label: Image
        name: image
        widget: image
  - name: weekday-deals
    label: Weekday Deals
    folder: content/weekday-deals
    fields:
      - name: title
        label: Title
        widget: string
      - name: description
        label: description
        widget: text
      - name: background
        label: Background
        widget: image
