backend:
  name: git-gateway
  branch: master

media_folder: static/uploads
public_folder: /uploads

collections:
  # - name: post
  #   label: Posts
  #   folder: src/pages/posts
  #   create: true
  #   slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
  #   fields:
  #     - { label: "Type", name: "type", widget: "hidden", default: "post" }
  #     - { label: "Title", name: "title", widget: "string" }
  #     - { label: "Publish Date", name: "date", widget: "datetime" }
  #     - { label: "Body", name: "body", widget: "markdown" }
  - name: menu-item
    label: Menu Item
    folder: src/pages/menu
    create: true
    fields:
      - { label: "Type", name: "type", widget: "hidden", default: "menu-item" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Price", name: "price", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
  - name: slider-images
    label: Slider Images
    folder: test
    create: true
    fields:
      - label: Title
        name: title
        widget: hidden
        default: slider-image
      - label: Slider Images
        name: slider-images
        widget: image
        media_library:
          config:
            multiple: true
