backend:
  name: git-gateway
  branch: master

media_folder: static/uploads
public_folder: /uploads

collections:
  - name: menu-item
    label: Menu Item
    folder: content/menu-items
    create: true
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Type, name: type, widget: hidden, default: menu-item }
      - { label: Price, name: price, widget: number }
      - { label: Description, name: description, widget: text }
  - name: slider-images
    label: Slider Images
    files:
      - file: content/slider-images/images.md
        name: slider-images
        label: Slider Images
        fields:
          - name: type
            widget: hidden
            default: slider-image
          - label: Images
            name: images
            widget: list
            field: { label: Image, name: image, widget: image }
  - name: weekday-deals
    label: Weekday Deals
    folder: content/weekday-deals
    fields:
      - name: title
        label: Title
        widget: string
      - name: description
        label: description
        widget: text
      - name: background
        label: Background
        widget: image
  - name: test
    label: Test
    files:
      - file: content/test/test.md
        name: test
        label: Test
        fields:
          - name: bool
            widget: boolean
          - name: code
            widget: code
          - name: date
            widget: date
          - name: datetime
            widget: datetime
          - name: file
            widget: file
          - name: image
            widget: image
          - name: "gallery"
            widget: "list"
            field:
              name: image
              widget: image
          - name: map
            widget: map
          - name: markdown
            widget: markdown
          - name: number
            widget: number
          - name: object
            widget: object
          - name: relation
            widget: relation
            collection: menu-items
          - name: select
            widget: select
            options:
              - { label: "Chicago", value: "ORD" }
              - { label: "Paris", value: "CDG" }
              - { label: "Tokyo", value: "HND" }
          - name: string
            widget: string
          - name: text
            widget: text
