backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: posts
    label: Posts
    folder: src/pages/posts
    create: true
    fields:
      - { label: text, name: text, widget: string }
