backend:
  name: git-gateway
  branch: master

media_folder: static/uploads
public_folder: /uploads

collections:
  # - name: post
  #   label: Posts
  #   folder: src/pages/posts
  #   create: true
  #   slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
  #   fields:
  #     - { label: "Type", name: "type", widget: "hidden", default: "post" }
  #     - { label: "Title", name: "title", widget: "string" }
  #     - { label: "Publish Date", name: "date", widget: "datetime" }
  #     - { label: "Body", name: "body", widget: "markdown" }
  - name: menu-item
    label: Menu Item
    folder: content/menu-items
    create: true
    fields:
      - { label: Type, name: type, widget: hidden, default: menu-item }
      - { label: Title, name: title, widget: string }
      - { label: Price, name: price, widget: string }
      - { label: Description, name: description, widget: text }
  - name: slider-images
    label: Slider Images
    folder: content/slider-images
    slug: "{{month}}-{{day}}-{{minute}}-{{slug}}"
    create: true
    identifier_field: image
    fields:
      - label: Type
        name: type
        widget: hidden
        default: slider-image
      - label: Image
        name: image
        widget: image
