backend:
  name: git-gateway
  branch: master

media_folder: static/uploads
public_folder: /uploads

collections:
  - name: posts
    label: Posts
    folder: content/posts
      fields:
        - {name: type, widget: hidden, default: post}
        - {name: title, label: Title, widget: string}
        - {name: date, label: Date, widget: datetime}
        - {name: body, label: Body, widget: markdown}
  - name: test
    label: Test
    files:
      - file: content/test/test.md
        name: test
        label: Test
        fields:
          - name: bool
            widget: boolean
          - name: code
            widget: code
          - name: date
            widget: date
          - name: datetime
            widget: datetime
          - name: file
            widget: file
          - name: image
            widget: image
          - name: "gallery"
            widget: "list"
            field:
              name: image
              widget: image
          - name: map
            widget: map
          - name: markdown
            widget: markdown
          - name: number
            widget: number
          - name: object
            widget: object
          - name: relation
            widget: relation
            collection: menu-items
          - name: select
            widget: select
            options:
              - { label: "Chicago", value: "ORD" }
              - { label: "Paris", value: "CDG" }
              - { label: "Tokyo", value: "HND" }
          - name: string
            widget: string
          - name: text
            widget: text
